# sig/employee.rbs
class Employee
  attr_reader name: string
  attr_reader security_level: Integer
  attr_reader email_address: Array[String]

  def initialize(name: String, security_level:Integer) -> void
  def access_granted?(level: Integer) -> bool
end
